language: csharp
solution: Calculator.sln
dotnet: 2.1.4
sudo: false
mono:
  - latest

script:
  - dotnet build Calculator/Calculator.sln -c Release
  - dotnet test -c Release --no-build Calculator/Calculator/Test/Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

after_script:
        - bash <(curl -s https://codecov.io/bash)