language: csharp
solution: ./Calculator/Calculator.sln
sudo: false

install:
  - nuget restore ./Calculator/Calculator.sln

script:
  - xbuild /p:Configuration=Release ./Calculator/Calculator.sln /p:TargetFrameworkVersion="v4.6"

after_script:
        - bash <(curl -s https://codecov.io/bash)