language: csharp
solution: Calculator.sln
dotnet: 4.6
mono:
  - latest

script:
  - dotnet build Calculator.sln -c Release
  - dotnet test -c Release --no-build Calculator/Test/Test.csproj /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
